sequenceDiagram

    actor User

    participant App as Music App (Frontend)
    participant Backend as Backend API
    participant Playlist
    participant Song
    participant Database

    User->>App: Select playlist (Playlist)
    App->>Backend: Request playlist (PlaylistID)
    Backend->>Playlist: getSongs()
    Playlist-->>Backend: List of Songs
    Backend-->>App: Playlist details
    App-->>User: Show playlist
    User->>App: Select song (Song)
    App->>Backend: addSong(UserID, PlaylistID, SongID)
    Backend->>Song: getSongId()
    Song-->>Backend: songId
    Backend->>Playlist: addSong(Song)

    alt Song is not already in the playlist

        Playlist->>Playlist: Add Song
        Playlist-->>Backend: Song added successfully
        Backend->>Database: savePlaylistSong(PlaylistID, SongID)
        Database-->>Backend: Saved
        Backend-->>App: true
        App-->>User: Song added to playlist

    else Song is already in the playlist

        Playlist-->>Backend: false
        Backend-->>App: false
        App-->>User: Song already exists in playlist

    end
